/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatp2p;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;

/**
 *
 * @author Vanilo
 */
public class Layout extends javax.swing.JFrame {

    Cliente cliente;

    /**
     * Creates new form Layout
     */
    public Layout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ipDestinoLabel = new javax.swing.JLabel();
        portaDestinoLabel = new javax.swing.JLabel();
        textoMSGLabel = new javax.swing.JLabel();
        ipDestino = new javax.swing.JTextField();
        portaDestino = new javax.swing.JTextField();
        textoMSG = new javax.swing.JTextField();
        chatPane = new javax.swing.JScrollPane();
        textoChat = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0};
        layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        getContentPane().setLayout(layout);

        ipDestinoLabel.setText("IP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(ipDestinoLabel, gridBagConstraints);

        portaDestinoLabel.setText("Porta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(portaDestinoLabel, gridBagConstraints);

        textoMSGLabel.setText("Texto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(textoMSGLabel, gridBagConstraints);

        ipDestino.setText("127.0.0.1");
        ipDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipDestinoActionPerformed(evt);
            }
        });
        ipDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ipDestinoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(ipDestino, gridBagConstraints);

        portaDestino.setText("12345");
        portaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaDestinoActionPerformed(evt);
            }
        });
        portaDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                portaDestinoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(portaDestino, gridBagConstraints);

        textoMSG.setText("Oi Mundo");
        textoMSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoMSGActionPerformed(evt);
            }
        });
        textoMSG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoMSGKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(textoMSG, gridBagConstraints);

        textoChat.setEditable(false);
        chatPane.setViewportView(textoChat);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 300;
        getContentPane().add(chatPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ipDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipDestinoActionPerformed

    private void portaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaDestinoActionPerformed

    private void textoMSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoMSGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMSGActionPerformed

    private void textoMSGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoMSGKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(cliente != null) {
                try {
                    cliente.enviarMensagem();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Conexão Recusada!");
                }
            }
        }
    }//GEN-LAST:event_textoMSGKeyPressed

    private void ipDestinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipDestinoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                if (cliente == null) {
                    cliente = new Cliente(new Socket(ipDestino.getText(),
                            Integer.parseInt(portaDestino.getText())));
                    cliente.iniciar(textoMSG, textoChat);
                } else {
                    cliente.fechar();
                    cliente = new Cliente(new Socket(ipDestino.getText(),
                            Integer.parseInt(portaDestino.getText())));
                    cliente.iniciar(textoMSG, textoChat);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Conexão Recusada!");
            }
        }
    }//GEN-LAST:event_ipDestinoKeyPressed

    private void portaDestinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_portaDestinoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                if (cliente == null) {
                    cliente = new Cliente(new Socket(ipDestino.getText(),
                            Integer.parseInt(portaDestino.getText())));
                    cliente.iniciar(textoMSG, textoChat);
                } else {
                    cliente.fechar();
                    cliente = new Cliente(new Socket(ipDestino.getText(),
                            Integer.parseInt(portaDestino.getText())));
                    cliente.iniciar(textoMSG, textoChat);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Conexão Recusada!");
            }
        }
    }//GEN-LAST:event_portaDestinoKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chatPane;
    private javax.swing.JTextField ipDestino;
    private javax.swing.JLabel ipDestinoLabel;
    private javax.swing.JTextField portaDestino;
    private javax.swing.JLabel portaDestinoLabel;
    private javax.swing.JTextPane textoChat;
    private javax.swing.JTextField textoMSG;
    private javax.swing.JLabel textoMSGLabel;
    // End of variables declaration//GEN-END:variables

    public JTextPane getTextoChat() {
        return textoChat;
    }
}
